### ISSUE TITLE
Gimp  2.10.8 giving error 28 

### ISSUE THREAD

**Issue by orosalsero1** [d-j-a-y/Gimp2Synfig#16]
Here is the error log as of 11/15/2018:

Traceback (most recent call last):
  File "C:\Program Files\GIMP 2\32\lib\gimp\2.0\python/gimpfu.py", line 740, in response
    dialog.res = run_script(params)
  File "C:\Program Files\GIMP 2\32\lib\gimp\2.0\python/gimpfu.py", line 361, in run_script
    return apply(function, params)
  File "C:\Program Files\GIMP 2\lib\gimp\2.0\plug-ins\synfigexport - Copy.py", line 236, in python_fu_exportsynfig
    "blend_method":gimp2synfig_mode_converter(l.mode), \
  File "C:\Program Files\GIMP 2\lib\gimp\2.0\plug-ins\synfigexport - Copy.py", line 179, in gimp2synfig_mode_converter
    return modes[mode]
KeyError: 28

I hope you can fix it, thank you very much

**Comment by d-j-a-y** [comment]
Thank to taking time to report ... but ... 

Please update to the last script version.
Before opening an issue, be sure to use the last version. 

 _"KeyError: 28" already reported (#15) and fixed by fb530e82e7c2dcec5a721a738e76fe1b57ba5617_

**Comment by neil-enjoy** [comment]
I am having a similar issue.  I can't see an error but am running gimp 2.10.8 and the plugin is not loading.  I see very briefly synfigfu in the startup window but there is no sifx filetype in the Export or Export As dialogs.
Has this been tested in this version of GIMP?

**Comment by d-j-a-y** [comment]
@neil-enjoy  , yep Gimp 2.10.8 + Synfig 1.3.11 + Gimp2Synfig  18.10.23 is ok... (by the way, sifz is synfig filetype not sifx)
